version: "3.8"

services:
  twitch-whitelist-bot:
    build: .
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_CHANNEL_NAME=${TWITCH_CHANNEL_NAME}
      - REWARD_ID=${REWARD_ID}
      - SCREEN_SESSION=${SCREEN_SESSION:-mcserver}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
